package com.bonus.lotteryFrame.sqlite.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bonus.lotteryFrame.entity.CostEntity;
import com.bonus.lotteryFrame.entity.CostRecordEntity;
import com.bonus.lotteryFrame.entity.HouseholdEntity;
import com.bonus.lotteryFrame.entity.UserEntity;

import com.bonus.lotteryFrame.sqlite.dao.CostEntityDao;
import com.bonus.lotteryFrame.sqlite.dao.CostRecordEntityDao;
import com.bonus.lotteryFrame.sqlite.dao.HouseholdEntityDao;
import com.bonus.lotteryFrame.sqlite.dao.UserEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig costEntityDaoConfig;
    private final DaoConfig costRecordEntityDaoConfig;
    private final DaoConfig householdEntityDaoConfig;
    private final DaoConfig userEntityDaoConfig;

    private final CostEntityDao costEntityDao;
    private final CostRecordEntityDao costRecordEntityDao;
    private final HouseholdEntityDao householdEntityDao;
    private final UserEntityDao userEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        costEntityDaoConfig = daoConfigMap.get(CostEntityDao.class).clone();
        costEntityDaoConfig.initIdentityScope(type);

        costRecordEntityDaoConfig = daoConfigMap.get(CostRecordEntityDao.class).clone();
        costRecordEntityDaoConfig.initIdentityScope(type);

        householdEntityDaoConfig = daoConfigMap.get(HouseholdEntityDao.class).clone();
        householdEntityDaoConfig.initIdentityScope(type);

        userEntityDaoConfig = daoConfigMap.get(UserEntityDao.class).clone();
        userEntityDaoConfig.initIdentityScope(type);

        costEntityDao = new CostEntityDao(costEntityDaoConfig, this);
        costRecordEntityDao = new CostRecordEntityDao(costRecordEntityDaoConfig, this);
        householdEntityDao = new HouseholdEntityDao(householdEntityDaoConfig, this);
        userEntityDao = new UserEntityDao(userEntityDaoConfig, this);

        registerDao(CostEntity.class, costEntityDao);
        registerDao(CostRecordEntity.class, costRecordEntityDao);
        registerDao(HouseholdEntity.class, householdEntityDao);
        registerDao(UserEntity.class, userEntityDao);
    }
    
    public void clear() {
        costEntityDaoConfig.clearIdentityScope();
        costRecordEntityDaoConfig.clearIdentityScope();
        householdEntityDaoConfig.clearIdentityScope();
        userEntityDaoConfig.clearIdentityScope();
    }

    public CostEntityDao getCostEntityDao() {
        return costEntityDao;
    }

    public CostRecordEntityDao getCostRecordEntityDao() {
        return costRecordEntityDao;
    }

    public HouseholdEntityDao getHouseholdEntityDao() {
        return householdEntityDao;
    }

    public UserEntityDao getUserEntityDao() {
        return userEntityDao;
    }

}
